#
# Makefile for APEX loader
#
#   Copyright (C) 2004 Marc Singer
#
#   This program is licensed under the terms of the GNU General Public
#   License as published by the Free Software Foundation.  Please refer
#   to the file debian/copyright for further details.
#

obj-$(CONFIG_ATAG) += atag.o
obj-$(CONFIG_USE_RAMDISK) += atag-initrd.o
