#
# Makefile for APEX loader
#

lib-y := vsprintf.o ctype.o udiv.o
lib-y += strlen.o string.o
lib-y += crc32.o xmodem.o
lib-y += env.o
#lib-y += div64.o

#CFLAGS_vsprintf.o += -mthumb
#CFLAGS_crc32.o = -mthumb -mthumb-interwork