#
# Makefile for APEX loader
#
#   Copyright (C) 2004 Marc Singer
#
#   This program is licensed under the terms of the GNU General Public
#   License as published by the Free Software Foundation.  Please refer
#   to the file debian/copyright for further details.
#

lib-y := div64.o memchr.o memzero.o
#lib-y += memcpy2.o
lib-y += memcpy.o
#lib-y += relocate.o
#lib-y += entry.o
lib-y += lib1funcs.o
lib-y += cp15.o
