#
# Makefile for APEX loader
#
#   Copyright (C) 2004 Marc Singer
#
#   This program is licensed under the terms of the GNU General Public
#   License as published by the Free Software Foundation.  Please refer
#   to the file debian/copyright for further details.
#

linklibs-$(CONFIG_NPE) += $(wildcard src/mach-$(CONFIG_MACH)/_intel/ixp400_xscale_sw/lib/linuxbe/lib*.a)
linklibs-$(CONFIG_NPE) += $(wildcard src/mach-$(CONFIG_MACH)/_intel/ixp_osal/lib/linux/linuxbe/ixp400/lib*.a)

