#
# Makefile for APEX loader
#
#   Copyright (C) 2004,2005 Marc Singer
#
#   This program is licensed under the terms of the GNU General Public
#   License as published by the Free Software Foundation.  Please refer
#   to the file debian/copyright for further details.
#

obj-$(CONFIG_DRIVER_LH_ADC)	+= adc.o
obj-$(CONFIG_DRIVER_LH_MMC)	+= drv-mmc.o
obj-$(CONFIG_DRIVER_LH_CLCDC)	+= drv-clcdc.o
obj-$(CONFIG_DRIVER_LH_I2C)	+= drv-i2c.o
