#!/usr/bin/perl

print "#if !defined (__CONFIG_H__)\n";
print "#define __CONFIG_H__\n";

while (<>) {

    next if m/^\s*#/;
    
    next if ! m/\s*([^=\s]+)\s*=\s*([^\s]+)/;
    print "#define $1 $2\n";
}

print "#endif /* __CONFIG_H__ */\n";
